dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/

# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: RMk7y97Rxn2rAFhDyNlRCrN8V9SdttcA603Hm4eHUWvJm8dYT8UN7+nSnxH8v2QDaEndaMzrEi9uOsEZ7xyJTXmabN2aXjlqGE+C5LDzBRNCU9gc0DcEwJ2JM1TQiSk0G3xFgy867FBevqLJ8QkE4Tp2i+3Z4v00hp+FbUtYxuslO9ImlvSgClTJzguoEl1ZlSMcy92V5yivrJWmwqdJ4PSNI2rYhlszOMjyf+oAuiNtYifNdmrLwkNI6ThzHjaHNVE+wP1jVU5BKeFn6NrU+oIcynJj30u768MveCBUlpG6UdCsUnnriQUuHKOPv8soOMCLP45hrqKsWSnhaUQHV7AxCqco6c1Pgd9tgXVydpNlBJ3UjhXWP99NaKstwQreHAoYSCZW2lsezrqn6M6ZtXw9WGlU02yNLDljehbo/hrfh9gnP+DRlMf70QKeGeL11hxNCJYZ+g486fyBEYMeN/zWYggr07iO8+3aMuBYGorTe3W8p0HM6moy245jF7NM/a1nUG6CGDb1bRtWLAymv+oGi21TTFf8F34YD1MbFQXMO62BhNJucvyy0mTf5KP2AXSqozLloiehg7V75W9xp/WMY17fSXsNZDWAZssMKAeku4Knqoq4p1NAtNx/+lQMJofnuPligd0fuLH/NzV+cG+ytcEt0z0BHKOFUUv8XtM=


# install mdl for checking Markdown
before_install:
  - gem install mdl

notifications:
  email: never

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pip install --upgrade codecov
  - pipenv install --dev

# perform testing:
# --> run the test suite with pytest and codecov
# --> Check for black format
# --> lint the functions with flake8
# --> lint the test suites with flake8
# --> lint the functions with pylint
# --> lint the test suites with pylint
# --> lint the README documentation with mdl
script:
  - shopt -s globstar
  - pipenv run pytest --cov-config pytest.cov --cov
  - pipenv run black **/*.py --check
  - pipenv run flake8 **/*.py
  - pipenv run pylint **/*.py
  - mdl README.md

# report coverage information to CodeCov
after_success:
  - codecov
